# Imports Base

In [1]:
import numpy as np
from fractions import Fraction
import sympy as sy


# 1)

In [2]:
#Realiza o método de eliminação de gauss iterativamente. Considera que não há zeros na diagonal principal
def pivotamento(mat):
    def pivot(mat,col=0,row=0):

        #Elimina a chance do elemento divisor ser 0
        r=1        
        while mat[row,col] == 0:
            mat[:,col],mat[:,col+r] = mat[:,col+r].copy(),mat[:,col].copy()
            r+=1
        mat[row] = mat[row]/mat[row,col]

        for l in range(row+1,len(mat)):
            mat[l] = mat[l] - mat[l,col]/mat[row,col] * mat[row]
            
    for r in range(len(mat)):
        pivot(mat,r,r)
        print('\n',mat)

#Algoritmo utilizado na questão 2


# 2)

In [3]:
#Cria a matriz do exercício
mat = np.array([2,2,1,1,7,
                1,-1,2,-1,1,
                3,2,-3,-2,4,
                4,3,2,1,12],dtype=np.float32).reshape(4,5)
mat

array([[ 2.,  2.,  1.,  1.,  7.],
       [ 1., -1.,  2., -1.,  1.],
       [ 3.,  2., -3., -2.,  4.],
       [ 4.,  3.,  2.,  1., 12.]], dtype=float32)

In [4]:
pivotamento(mat)


 [[ 1.   1.   0.5  0.5  3.5]
 [ 0.  -2.   1.5 -1.5 -2.5]
 [ 0.  -1.  -4.5 -3.5 -6.5]
 [ 0.  -1.   0.  -1.  -2. ]]

 [[ 1.    1.    0.5   0.5   3.5 ]
 [-0.    1.   -0.75  0.75  1.25]
 [ 0.    0.   -5.25 -2.75 -5.25]
 [ 0.    0.   -0.75 -0.25 -0.75]]

 [[ 1.          1.          0.5         0.5         3.5       ]
 [-0.          1.         -0.75        0.75        1.25      ]
 [-0.         -0.          1.          0.52380955  1.        ]
 [ 0.          0.          0.          0.14285716  0.        ]]

 [[ 1.          1.          0.5         0.5         3.5       ]
 [-0.          1.         -0.75        0.75        1.25      ]
 [-0.         -0.          1.          0.52380955  1.        ]
 [ 0.          0.          0.          1.          0.        ]]


# 5)
    Estratégia de pivoteamento parcial
    No início de cada eliminação de Gauss, trocando as linhas se necessário,
    escolher para o pivô o maior 𝑎𝑖𝑗 da coluna 𝑗 (com 𝑖 ≥ 𝑗).

In [23]:
def gauss_pivotparcial(mat):
    def pivotparcial(mat:np.array,row=0,col=0):

        maior = np.argmax(mat[row:,col]) #Encontra a linha com o maior pivot na coluna especificada
        mat[col],mat[maior] = mat[maior].copy(),mat[col].copy()
        
        '''   r=1
            while mat[row,col] == 0:
                mat[:,col],mat[:,col+r] = mat[:,col+r].copy(),mat[:,col].copy()
                r+=1'''
        mat[row] = mat[row]/mat[row,col]
        for l in range(row+1,len(mat)):
            mat[l] = mat[l] - mat[l,col]/mat[row,col] * mat[row]
    
    for c in range(len(mat)):
        pivotparcial(mat,c,c)

    '''for c in range(len(mat)):
        
        posmax = mat[:,c].argmax() if mat[:,c].argmax()>c else c
        print(posmax)
        print(mat)
        mat[c],mat[posmax] = mat[posmax].copy(),mat[c].copy()'''

In [25]:
matriz = np.array([1,2,5,3,2,1,3,7,3,4,0,5,2,2,1,1,3,0,1,2,0,6,7,4,7],dtype=np.float32).reshape(5,5)
print(matriz)
gauss_pivotparcial(matriz)
matriz[:,0].argmax()
matriz

[[1. 2. 5. 3. 2.]
 [1. 3. 7. 3. 4.]
 [0. 5. 2. 2. 1.]
 [1. 3. 0. 1. 2.]
 [0. 6. 7. 4. 7.]]


array([[ 0.        , -0.22222233,  1.1111116 ,  0.        ,  5.6296296 ],
       [ 0.        ,  0.        ,  0.        , -1.1111112 ,  1.7407408 ],
       [ 0.        ,  0.        ,  1.        ,  0.44444445,  0.03703704],
       [-0.        , -0.5       ,  2.5       ,  1.        , -0.        ],
       [ 0.5       ,  1.        ,  2.5       ,  1.5       ,  1.        ]],
      dtype=float32)

# Fatoração LU
# 6)

In [2]:
def fatoraLU(A):  
    U = np.copy(A)  
    n = np.shape(U)[0]  
    L = np.eye(n)  
    for j in np.arange(n-1):  
        for i in np.arange(j+1,n):  
            L[i,j] = U[i,j]/U[j,j]  
            for k in np.arange(j+1,n):  
                U[i,k] = U[i,k] - L[i,j]*U[j,k]  
            U[i,j] = 0  
    return L, U

In [27]:
#Resolvendo a questão 2 por LU
#Recria a matriz do exercício
mat = np.array([2,2,1,1,
                1,-1,2,-1,
                3,2,-3,-2,
                4,3,2,1],dtype=np.float32).reshape(4,4)

l,u = fatoraLU(mat)
print(l)
print(u)


[[1.         0.         0.         0.        ]
 [0.5        1.         0.         0.        ]
 [1.5        0.5        1.         0.        ]
 [2.         0.5        0.14285715 1.        ]]
[[ 2.          2.          1.          1.        ]
 [ 0.         -2.          1.5        -1.5       ]
 [ 0.          0.         -5.25       -2.75      ]
 [ 0.          0.          0.          0.14285716]]


# 8)

In [20]:
mat8 = np.array([2,4,0,4,6,3,-6,-10,0]).reshape(3,3)
l,u = fatoraLU(mat8)

In [5]:
#i)
resulti = np.array([2,1,-6])

#ii)
resultii = np.array([1]*3)

#iii) 
resultiii = np.array([2,1,-6])

#iv)
resultiv = np.array([1,2,3])

print('l:\n',l)
print('u:\n',u)

l:
 [[ 1.  0.  0.]
 [ 2.  1.  0.]
 [-3. -1.  1.]]
u:
 [[ 2  4  0]
 [ 0 -2  3]
 [ 0  0  3]]


# Gauss - Jacobi

    Transformar Ax = b em x = Cx + g
    x**(k+1) = Cx**(k) + g

    - Transforma A em uma matriz Diagonal + Matriz Diagonal nula
    - Manipular

https://prnt.sc/26i6nc6 Cálculos

https://prnt.sc/26i6nvb Resumo



In [44]:
import numpy as np
def jacobi(A,x:np.ndarray,b:np.ndarray,precisao:float):
    """Realiza o método iterativo de Gauss-Jacobi para aproximar o valor de x uma vez

    Args:
        A (np.matrix): Original coef matrix of Ax = b
        x (np.ndarray): Inicial guess of the values that satisfies the linear system
        b (np.ndarray): Vector of results from the linear system
    """


    # diagflat cria uma matriz com apenas a diagonal definida, restante 0. np.diagonal obtém um vetor que representa a diagonal da Matriz
    
    D = np.diagflat(np.diagonal(A)) #Matriz Diagonal com restante 0
    M = A - D #Matriz com a diagonal zerada
    Dinv = np.diagflat(1/np.diagonal(A))#np.linalg.inv(D)
    C = -(Dinv@M)
    g = Dinv@b
    x = C@x + g

    #Iteração
    #x[0] = (Dinv[0,0])*(b[0]-sum(D[0,1:]*x[1:]))
    #for n in range(len(x)):
    #    x[n] = Dinv[n,n] * (b[n]-sum(D[n,:]*x)+x[n]*D[n,n])
    print(x)
    print(A@x)

    if max(A@x - b)<precisao: #Critério de parada
        return x
    
    return jacobi(A,x,b,precisao) #Recursão





In [51]:
mat = np.array([2,2,1,1,
                1,-1,2,-1,
                3,2,-3,-2,
                4,3,2,1],dtype=np.float32).reshape(4,4)
jacobi(mat,np.array([1,2,2,1]),np.array([7,1,4,12]),.001)

#mat@np.array([1,2,1,0])

[ 0.          3.          0.33333331 -2.        ]
[ 4.33333331 -0.33333337  9.00000006  7.66666663]
[1.33333334 1.66666663 2.00000006 2.33333337]
[10.33333337  1.33333346 -3.33333364 16.66666675]
[-0.33333334  2.00000009 -0.44444454 -2.33333337]
[ 0.55555558 -0.88888914  9.00000052  1.44444444]
[2.88888887 0.11111095 1.22222234 8.22222219]
[ 15.44444416  -2.99999958 -11.22222291  22.55555519]
[-1.33333321 -3.88888863 -3.85185216 -2.33333301]
[-16.62962885  -2.8148159    4.44444559 -27.03703607]
[10.48148121 -7.70370452 -3.7037037  36.70370306]
[ 38.55555273 -25.92592472 -46.25926044  48.11110693]
[ -5.29629515 -34.62962925 -20.45679143   0.59259613]
[ -99.71604411  -12.17284491  -24.96296193 -165.3950551 ]


array([ -5.29629515, -34.62962925, -20.45679143,   0.59259613])