# Imports Base

In [59]:
import numpy as np
from fractions import Fraction
import sympy as sy
import matplotlib.pyplot as plt

# 1)

In [60]:
#Realiza o método de eliminação de gauss iterativamente. Considera que não há zeros na diagonal principal
def pivotamento(mat):
    def pivot(mat,col=0,row=0):

        #Elimina a chance do elemento divisor ser 0
        r=1        
        while mat[row,col] == 0:
            mat[:,col],mat[:,col+r] = mat[:,col+r].copy(),mat[:,col].copy()
            r+=1

        mat[row] = mat[row]/mat[row,col]

        for l in range(row+1,len(mat)):
            mat[l] = mat[l] - mat[l,col]/mat[row,col] * mat[row]
            
    for r in range(len(mat)): #Realiza o pivotamento para cada elemento da diagonal
        pivot(mat,r,r)
        #print('\n',mat) #Printa passo a passo

#Algoritmo utilizado na questão 2


# 2)

In [61]:
#Cria a matriz do exercício
mat = np.array([2,2,1,1,7,
                1,-1,2,-1,1,
                3,2,-3,-2,4,
                4,3,2,1,12],dtype=np.float32).reshape(4,5)
mat

array([[ 2.,  2.,  1.,  1.,  7.],
       [ 1., -1.,  2., -1.,  1.],
       [ 3.,  2., -3., -2.,  4.],
       [ 4.,  3.,  2.,  1., 12.]], dtype=float32)

In [62]:
pivotamento(mat)
mat

array([[ 1.        ,  1.        ,  0.5       ,  0.5       ,  3.5       ],
       [-0.        ,  1.        , -0.75      ,  0.75      ,  1.25      ],
       [-0.        , -0.        ,  1.        ,  0.52380955,  1.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ,  0.        ]],
      dtype=float32)

# 3)

In [63]:
n=10
mat3 = [[0]*n for _ in range(n)]
mat3[0][:2] = [2,-2]
mat3[n-1][-2:] = [-1,2]
for l in range(1,n-1): #linha
    mat3[l][l-1] = -1
    mat3[l][l] = 2
    mat3[l][l+1] = -1
    
mat3

[[2, -2, 0, 0, 0, 0, 0, 0, 0, 0],
 [-1, 2, -1, 0, 0, 0, 0, 0, 0, 0],
 [0, -1, 2, -1, 0, 0, 0, 0, 0, 0],
 [0, 0, -1, 2, -1, 0, 0, 0, 0, 0],
 [0, 0, 0, -1, 2, -1, 0, 0, 0, 0],
 [0, 0, 0, 0, -1, 2, -1, 0, 0, 0],
 [0, 0, 0, 0, 0, -1, 2, -1, 0, 0],
 [0, 0, 0, 0, 0, 0, -1, 2, -1, 0],
 [0, 0, 0, 0, 0, 0, 0, -1, 2, -1],
 [0, 0, 0, 0, 0, 0, 0, 0, -1, 2]]

# Fatoração LDU

In [64]:
def LDU(A):
    U = np.copy(A)
    D = np.diagflat(np.diagonal(U))
    n = np.shape(U)[0] #nº de Linhas da matriz
    L = np.eye(n) #Identidade
    cont = 0 
    for j in np.arange(n-1): #Pelas colunas

        for i in np.arange(j+1,n):  #Pelas linhas

            L[i,j] = U[i,j]/U[j,j] #representa o m # no L são salvos os multiplicadores da posição pelo pivot
            U[i] = U[i] - L[i,j]*U[j]
    

    return L, D, U



In [65]:
x = np.array([[1,2],[3,4]])


Fatora LDU:

Fatora Ly = B
descobre um vetor y, que substitui o resultado
Dz = y

encontra um vetor z
Ux = z

Encontra finalmente x

# 5)
    Estratégia de pivoteamento parcial
    No início de cada eliminação de Gauss, trocando as linhas se necessário,
    escolher para o pivô o maior 𝑎𝑖𝑗 da coluna 𝑗 (com 𝑖 ≥ 𝑗).

In [66]:
matriz5 = np.array([0,1,2,3,4,
                    2,0,1,-1,0,
                    3,-2,0,1,2,
                    0,1,-2,0,2,
                    1,3,-2,1,0
                    ],dtype=np.float32).reshape(5,5)
col = 1
ordenada=np.sort(np.abs(matriz5[:,col]))[::-1]

for i,c in enumerate(ordenada):
    if np.where(np.abs(matriz5[:,col])==abs(c))[0][0]>=col:
        return(np.where(np.abs(matriz5[:,col])==abs(c))[0][0])

SyntaxError: 'return' outside function (Temp/ipykernel_11132/1288390526.py, line 12)

In [ ]:
def gauss_pivotparcial(mat,steps=False):

    def maiorargpivot(mat,col):
        """Descobre o maior pivot da coluna atual e retorna seu index, 
        para realizar a permutação

        Args:
            mat ([np.ndarray]): [numpy matrix]
            col ([int]): [column index]
        
        Returns:
            Maior index da coluna
        """
        ordenada=np.sort(np.abs(mat[:,col]))[::-1]

        for i,c in enumerate(ordenada):
            if np.where(np.abs(mat[:,col])==abs(c))[0][0]>=col: #Caso o maior valor esteja em posição válida para se tornar o novo pivot
                return(np.where(np.abs(mat[:,col])==abs(c))[0][0]) #Retorna a posição


    def pivotparcial(mat:np.array,row=0,col=0): 

        maior = maiorargpivot(mat,col) #Encontra o maior elemento da linha

        if row<maior:
            mat[row],mat[maior] = mat[maior].copy(),mat[row].copy()

        mat[row] = mat[row]/mat[row,col]
        for l in range(row+1,len(mat)):
            if mat[l,col]!= 0:
                mat[l] = mat[l] - mat[l,col]/mat[row,col] * mat[row]
    
    for c in range(len(mat)-1):
        pivotparcial(mat,c,c)
        if steps:
            print(mat)
    print(mat)
    

In [ ]:
matriz5 = np.array([0,1,2,3,4,
                    2,0,1,-1,0,
                    3,-2,0,1,2,
                    0,1,-2,0,2,
                    1,3,-2,1,0
                    ],dtype=np.float32).reshape(5,5)
print(matriz)
res5 = np.array([8,3,9,5,6])

#gauss_pivotparcial(matriz)

np.linalg.solve(matriz5,res5)

[[ 1.         -0.6666667   0.          0.33333334  0.6666667 ]
 [ 0.          1.         -0.54545456  0.18181817 -0.18181819]
 [ 0.          0.          1.          1.1071428   1.6428571 ]
 [ 0.          0.          0.          1.4285715   4.5714283 ]
 [ 0.          0.          0.         -3.8214285  -3.9285712 ]]


array([ 2.14457831,  0.6626506 , -0.57831325,  0.71084337,  1.59036145])

# Fatoração LU
# 6)

In [ ]:
def fatoraLU(A):  
    U = np.copy(A) 
    n = np.shape(U)[0] #nº de Linhas da matriz
    L = np.eye(n) #Identidade
    cont = 0 
    for j in np.arange(n-1): #Pelas colunas
        '''while U[j,j]==0:
            print(U[j])
            cont+=1
            U[j],U[j+cont] = U[j+cont].copy(),U[j].copy()'''

        for i in np.arange(j+1,n):  #Pelas linhas

            L[i,j] = U[i,j]/U[j,j] #representa o m # no L são salvos os multiplicadores da posição pelo pivot
            U[i] = U[i] - L[i,j]*U[j]
            
            
            

    return L, U

def solveL(L,b):

    y = np.zeros(L.shape[1])
    for i in range(len(b)+1):
        soma = 0
        for j in range(i):
            soma += L[i][j]*y[j]

        y[i] = b[i]-soma

    return y

def solveU(U,y):
    n = len(y)-1
#Vetor cheio de 0 de n de tamanho  
    x = np.zeros(y.shape)
    x[n] = b[n]/U[n][n]

    for i in range(n-1,0,-1):
        soma = 0
        for j in range(i-1,n+2):
            soma = soma + U[i][j]*x[j]

        x[i] = (b[i]-soma)/U[i][i]

    return x



In [ ]:
#Resolvendo a questão 2 por LU
#Recria a matriz do exercício
mat = np.array([2,2,1,1,
                1,-1,2,-1,
                3,2,-3,-2,
                4,3,2,1],dtype='float32').reshape(4,4)

l,u = fatoraLU(mat)
print(l)
print(u)

#Conferindo
print(l@u)


[[1.         0.         0.         0.        ]
 [0.5        1.         0.         0.        ]
 [1.5        0.5        1.         0.        ]
 [2.         0.5        0.14285715 1.        ]]
[[ 2.0000000e+00  2.0000000e+00  1.0000000e+00  1.0000000e+00]
 [ 0.0000000e+00 -2.0000000e+00  1.5000000e+00 -1.5000000e+00]
 [ 0.0000000e+00  0.0000000e+00 -5.2500000e+00 -2.7500000e+00]
 [ 0.0000000e+00  0.0000000e+00  5.9604645e-08  1.4285716e-01]]
[[ 2.          2.          1.          1.        ]
 [ 1.         -1.          2.         -1.        ]
 [ 3.          2.         -3.         -2.        ]
 [ 4.          3.          2.00000003  1.        ]]


# 8)

In [ ]:
mat8 = np.array([2,4,0,4,6,3,-6,-10,0]).reshape(3,3)
l,u = fatoraLU(mat8)


In [ ]:
#i)
resulti = np.array([2,1,-6])

#ii)
resultii = np.array([1]*3)

#iii) 
resultiii = np.array([2,2,0])

#iv)
resultiv = np.array([1,2,3])

print('l:\n',l)
print('u:\n',u)

l:
 [[ 1.  0.  0.]
 [ 2.  1.  0.]
 [-3. -1.  1.]]
u:
 [[ 2  4  0]
 [ 0 -2  3]
 [ 0  0  3]]


In [ ]:
np.linalg.solve(mat8,resultiv)

array([-5.5,  3. ,  2. ])

# Gauss - Jacobi

    Transformar Ax = b em x = Cx + g
    x**(k+1) = Cx**(k) + g

    - Transforma A em uma matriz Diagonal + Matriz Diagonal nula
    - Manipular

https://prnt.sc/26i6nc6 Cálculos

https://prnt.sc/26i6nvb Resumo



In [ ]:
def jacobi(A,x:np.ndarray,b:np.ndarray,precisao:float,xlist=None):
    """Realiza o método iterativo de Gauss-Jacobi para aproximar o valor de x uma vez

    Args:
        A (np.matrix): Original coef matrix of Ax = b
        x (np.ndarray): Inicial guess of the values that satisfies the linear system
        b (np.ndarray): Vector of results from the linear system
    """

    def maiorargpivot(mat,col):

        """Descobre o maior pivot da coluna atual e retorna seu index, 
        para realizar a permutação

        Args:
            mat ([np.ndarray]): [numpy matrix]
            col ([int]): [column index]
        
        Returns:
            Maior index da coluna
        """
        ordenada=np.sort(np.abs(mat[:,col]))[::-1]

        for i,c in enumerate(ordenada):
            if np.where(np.abs(mat[:,col])==abs(c))[0][0]>=col: #Caso o maior valor esteja em posição válida para se tornar o novo pivot
                return(np.where(np.abs(mat[:,col])==abs(c))[0][0]) #Retorna a posição
    
    if xlist is None:
        xlist = []
    if len(xlist)>1 and max(abs(xlist[-1] - xlist[-2]))<precisao: #Critério de parada
        return x
    
    # Organiza a matriz de forma a satisfazer o critério de convergência da melhor forma
    for ind,l in enumerate(A):
        maior_da_coluna = maiorargpivot(A,ind)
        if maior_da_coluna!= ind:
            A[ind],A[maior_da_coluna] = A[maior_da_coluna].copy(),l.copy()

    
    # diagflat cria uma matriz com apenas a diagonal definida, restante 0. np.diagonal obtém um vetor que representa a diagonal da Matriz
    
    D = np.diagflat(np.diagonal(A)) #Matriz Diagonal com restante 0
    M = A - D #Matriz com a diagonal zerada
    Dinv = np.diagflat(1/np.diagonal(A)) #np.linalg.inv(D)
    C = -(Dinv@M)
    g = (Dinv@b)
    x = C@x + g #Próximo x

    print(x)
    xlist.append(x)
    
    return jacobi(A,x,b,precisao,xlist) #Recursão


exemplejacobi = np.array([10,2,1,1,5,1,2,3,10]).reshape(3,3)
res = np.array([7,-8,6])
jacobi(exemplejacobi,np.array([.7,-1.5,.6]),res,.0001)


[ 0.94 -1.86  0.91]
[ 0.981 -1.97   0.97 ]
[ 0.997  -1.9902  0.9948]
[ 0.99856 -1.99836  0.99766]
[ 0.999906 -1.999244  0.999796]
[ 0.9998692 -1.9999404  0.999792 ]
[ 1.00000888 -1.99993224  1.00000828]
[ 0.99998562 -2.00000343  0.9999779 ]


array([ 0.99998562, -2.00000343,  0.9999779 ])

# Gauss - Seidel

In [122]:
def seidel(A,x:np.ndarray,b:np.ndarray,precisao:float,xlist=None):
    """Realiza o método iterativo de Gauss-Jacobi para aproximar o valor de x uma vez

    Args:
        A (np.matrix): Original coef matrix of Ax = b
        x (np.ndarray): Initial guess of the values that satisfies the linear system
        b (np.ndarray): Vector of results from the linear system
    """
    
    def maiorargpivot(mat,col):

        """Descobre o maior pivot da coluna atual e retorna seu index, 
        para realizar a permutação

        Args:
            mat ([np.ndarray]): [numpy matrix]
            col ([int]): [column index]
        
        Returns:
            Maior index da coluna
        """
        ordenada=np.sort(np.abs(mat[:,col]))[::-1]

        for i,c in enumerate(ordenada):
            if np.where(np.abs(mat[:,col])==abs(c))[0][0]>=col: #Caso o maior valor esteja em posição válida para se tornar o novo pivot
                return(np.where(np.abs(mat[:,col])==abs(c))[0][0]) #Retorna a posição
    # Organiza a matriz de forma a satisfazer o critério de convergência da melhor forma
    
    if xlist is None:
        xlist = []

    for ind,l in enumerate(A):
        maior_da_coluna = maiorargpivot(A,ind)
        if maior_da_coluna!= ind:
            A[ind],A[maior_da_coluna] = A[maior_da_coluna].copy(),l.copy()

    if len(xlist)>1 and max(np.abs(xlist[-1] - xlist[-2]))<precisao: #Critério de parada
        return xlist[-1]

    # diagflat cria uma matriz com apenas a diagonal definida, restante 0. np.diagonal obtém um vetor que representa a diagonal da Matriz
    D = np.diagflat(np.diagonal(A)) #Matriz Diagonal com restante 0
    M = A - D # Matriz com a diagonal zerada
    Dinv = np.diagflat(1/np.diagonal(A))
    C = -(Dinv@M) # @ Representa uma multiplicação de matrizes, equivale a np.matmul (https://numpy.org/doc/stable/reference/generated/numpy.matmul.html)
    g = (Dinv@b)

    print(x)

    #Iteração 
    for n in range(len(x)):
        #Para cada iteração, utiliza o valor ja calculado, que foi salvo em x
        x[n] = (Dinv[n,n]*(b[n]-sum(M[n]*x)))
        
    xlist.append(x)


    return seidel(A,x,b,precisao,xlist) #Recursão


exempleseidel = np.array([10,2,1,1,5,1,2,3,10],dtype = 'float').reshape(3,3)
res = np.array([7,-8,6],dtype='float')
seidel(exempleseidel,np.array([.7,-1.5,.6],dtype='float'),res,.001)



[ 0.7 -1.5  0.6]
[ 0.94   -1.908   0.9844]


array([ 0.98316  , -1.993512 ,  1.0014216])

In [118]:
a1=np.array([ 0.7 ,-1.5,  0.6])
a2=np.array([ 0.94,   -1.908  , 0.9844])
print((a1-a2))
print(np.max(abs(a1-a2))<.5)

[-0.24    0.408  -0.3844]
True


# 12)

In [ ]:
lkc = np.array([3,-1,0,0,
-1,3,-1,0,
0,-1,3,-1,
0,0,-1,3],dtype=np.float32).reshape(4,4)

chute = np.array([50,20,10,5])
b = np.array([127,0,0,0]) 

jacobi(lkc,chute,b,precisao =.001)



[49.00000146 20.0000006   8.33333358  3.33333343]
[49.00000166 19.11111225  7.77777824  2.77777794]
[48.70370553 18.9259272   7.29629695  2.59259282]
[48.64197718 18.66666805  7.17284022  2.43209906]
[48.55555746 18.60493969  7.03292258  2.39094681]
[48.53498134 18.5294939   6.99862904  2.3443076 ]
[48.50983275 18.51120401  6.95793404  2.33287642]
[48.50373612 18.48925615  6.94802702  2.31931142]
[48.49642016 18.4839216   6.93618939  2.31600907]
[48.49464198 18.47753707  6.93331043  2.3120632 ]
[48.4925138  18.47598469  6.92986696  2.31110355]
[48.49199634 18.47412747  6.92902962  2.30995572]
[48.49137727 18.47367587  6.92802794  2.30967661]
[48.49122674 18.47313562  6.92778437  2.30934271]


array([48.49122674, 18.47313562,  6.92778437,  2.30934271])

# 13)

In [130]:
mat13 = np.array([4,1,1,1,
                2,-8,1,-1,
                1,2,-5,1,
                1,1,1,-4],dtype='float32').reshape(4,4)

b13 = np.array([7,-6,-1,-1],dtype='float32')
print(seidel(mat13,x=np.array([3,1,0,-1],dtype='float'),b=b13,precisao=10**-4))

[ 3.  1.  0. -1.]
[1.75       1.3125     0.87500001 1.234375  ]
[0.89453125 0.92871094 0.99726564 0.95512696]


# 14)

In [131]:
mat14 = np.array([5,-1,2,-1,1,9,-3,4,0,3,-7,2,-2,2,-3,10],dtype='float32').reshape(4,4)
b14= np.array([5,26,-7,33])
x14=np.array([0,3,1,4])
jacobi(mat14,x=x14,b=b14,precisao = 10**-3)

[2.00000003 1.44444446 3.42857163 3.00000005]
[0.51746026 2.47619056 2.47619063 4.43968269]
[1.39269842 1.6835979  3.32970548 3.6511112 ]
[0.73505964 2.2213304  2.76471674 4.24073184]
[1.18652577 1.84401817 3.16363658 3.83216095]
[0.8697812  2.10841562 2.88519679 4.11759258]
[1.09112294 1.92393768 3.08006188 3.91783223]
[0.93632924 2.05308157 2.94392552 4.0574557 ]
[1.04453726 1.96284721 3.03916532 3.95982727]
[0.96886878 2.02596111 2.97259961 4.02808769]
[1.02176993 1.98184218 3.01915141 3.9803615 ]
[0.98478019 2.01269318 2.98660724 4.01373105]
[1.01064197 1.99112418 3.00936326 3.99039966]
[0.99255948 2.0062055  2.99345329 4.00671262]
[1.00520232 1.99566114 3.00457756 3.99530686]
[0.99636259 2.00303369 2.99679976 4.00328159]
[1.00254317 1.99787896 3.00223791 3.99770579]
[0.9982218  2.00148308 2.99843566 4.0016043 ]
[1.00124323 1.99896315 3.00109414 3.99887852]
[0.99913069 2.00072505 2.99923538 4.00078434]
[1.00060774 1.99949316 3.000535   3.99945182]
[0.99957501 2.00035448 2.99962632 

array([1.00029708, 1.99975226, 3.00026165, 3.99973209])