In [111]:
import numpy as np
from fractions import Fraction
import sympy as sy


In [112]:
mat = np.array([2,2,1,1,7,
                1,-1,2,-1,1,
                3,2,-3,-2,4,
                4,3,2,1,12],dtype=np.float32).reshape(4,5)
mat

array([[ 2.,  2.,  1.,  1.,  7.],
       [ 1., -1.,  2., -1.,  1.],
       [ 3.,  2., -3., -2.,  4.],
       [ 4.,  3.,  2.,  1., 12.]], dtype=float32)

In [113]:
#Realiza o método de eliminação de gauss iterativamente
def pivot(mat,col=0,row=0):
    mat[row] = mat[row]/mat[row,col]

    for l in range(row+1,len(mat)):
        mat[l] = mat[l] - mat[l,col]/mat[row,col] * mat[row]

for r in range(len(mat)):
   
    pivot(mat,r,r)
    print('\n',mat)


 [[ 1.   1.   0.5  0.5  3.5]
 [ 0.  -2.   1.5 -1.5 -2.5]
 [ 0.  -1.  -4.5 -3.5 -6.5]
 [ 0.  -1.   0.  -1.  -2. ]]

 [[ 1.    1.    0.5   0.5   3.5 ]
 [-0.    1.   -0.75  0.75  1.25]
 [ 0.    0.   -5.25 -2.75 -5.25]
 [ 0.    0.   -0.75 -0.25 -0.75]]

 [[ 1.          1.          0.5         0.5         3.5       ]
 [-0.          1.         -0.75        0.75        1.25      ]
 [-0.         -0.          1.          0.52380955  1.        ]
 [ 0.          0.          0.          0.14285716  0.        ]]

 [[ 1.          1.          0.5         0.5         3.5       ]
 [-0.          1.         -0.75        0.75        1.25      ]
 [-0.         -0.          1.          0.52380955  1.        ]
 [ 0.          0.          0.          1.          0.        ]]


In [114]:
np.linalg.solve(mat[:,:-1],mat[:,-1])

array([1., 2., 1., 0.], dtype=float32)

# Fatoração LU