# Imports Base

In [64]:
import numpy as np
from fractions import Fraction
import sympy as sy
import matplotlib.pyplot as plt

# 1)

In [65]:
#Realiza o método de eliminação de gauss iterativamente. Considera que não há zeros na diagonal principal
def pivotamento(mat):
    def pivot(mat,col=0,row=0):

        #Elimina a chance do elemento divisor ser 0
        r=1        
        while mat[row,col] == 0:
            mat[:,col],mat[:,col+r] = mat[:,col+r].copy(),mat[:,col].copy()
            r+=1

        mat[row] = mat[row]/mat[row,col]

        for l in range(row+1,len(mat)):
            mat[l] = mat[l] - mat[l,col]/mat[row,col] * mat[row]
            
    for r in range(len(mat)): #Realiza o pivotamento para cada elemento da diagonal
        pivot(mat,r,r)
        #print('\n',mat) #Printa passo a passo

#Algoritmo utilizado na questão 2


# 2)

In [66]:
#Cria a matriz do exercício
mat = np.array([2,2,1,1,7,
                1,-1,2,-1,1,
                3,2,-3,-2,4,
                4,3,2,1,12],dtype=np.float32).reshape(4,5)
mat

array([[ 2.,  2.,  1.,  1.,  7.],
       [ 1., -1.,  2., -1.,  1.],
       [ 3.,  2., -3., -2.,  4.],
       [ 4.,  3.,  2.,  1., 12.]], dtype=float32)

In [67]:
pivotamento(mat)
mat

array([[ 1.        ,  1.        ,  0.5       ,  0.5       ,  3.5       ],
       [-0.        ,  1.        , -0.75      ,  0.75      ,  1.25      ],
       [-0.        , -0.        ,  1.        ,  0.52380955,  1.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ,  0.        ]],
      dtype=float32)

# 3)

In [68]:
#Gerando a matriz aumentada
n=10
mat3 = [[0]*(n+1) for _ in range(n)]
mat3[0][:2] = [2,-2]
mat3[0][-1] = 1
mat3[n-1][-3:-1] = [-1,2]
for l in range(1,n-1): #linha
    mat3[l][l-1] = -1
    mat3[l][l] = 2
    mat3[l][l+1] = -1
    
mat3=np.array(mat3,dtype=np.float32)
mat3


array([[ 2., -2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [-1.,  2., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., -1.,  2., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., -1.,  2., -1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -1.,  2., -1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., -1.,  2., -1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., -1.,  2., -1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0., -1.,  2., -1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  2., -1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  2.,  0.]],
      dtype=float32)

In [69]:
#Pivotando utilizando de sua estrutura
def pivot_tridiagonal(mat):
    def pivot(mat,row,col):

        mat[row] = mat[row].copy()/mat[row,col]
        for l in range(row+1,len(mat)):
            if mat[l,col]!= 0:
                mat[l] = mat[l] - mat[l,col]/mat[row,col] * mat[row]

    for r in range(len(mat)):
        pivot(mat,r,r)
pivot_tridiagonal(mat3)
mat3


array([[ 1. , -1. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0.5],
       [ 0. ,  1. , -1. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0.5],
       [ 0. ,  0. ,  1. , -1. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0.5],
       [ 0. ,  0. ,  0. ,  1. , -1. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0.5],
       [ 0. ,  0. ,  0. ,  0. ,  1. , -1. ,  0. ,  0. ,  0. ,  0. ,  0.5],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  1. , -1. ,  0. ,  0. ,  0. ,  0.5],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  1. , -1. ,  0. ,  0. ,  0.5],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  1. , -1. ,  0. ,  0.5],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  1. , -1. ,  0.5],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  1. ,  0.5]],
      dtype=float32)

# Fatoração LDU

Fatora LDU:

Fatora Ly = B
descobre um vetor y, que substitui o resultado
Dz = y

encontra um vetor z
Ux = z

Encontra finalmente x

# 5)
    Estratégia de pivoteamento parcial
    No início de cada eliminação de Gauss, trocando as linhas se necessário,
    escolher para o pivô o maior 𝑎𝑖𝑗 da coluna 𝑗 (com 𝑖 ≥ 𝑗).

In [70]:
def gauss_pivotparcial(mat,steps=False):

    def maiorargpivot(mat,col):
        """Descobre o maior pivot da coluna atual e retorna seu index, 
        para realizar a permutação

        Args:
            mat ([np.ndarray]): [numpy matrix]
            col ([int]): [column index]
        
        Returns:
            Maior index da coluna
        """
        ordenada=np.sort(np.abs(mat[:,col]))[::-1]

        for i,c in enumerate(ordenada):
            if np.where(np.abs(mat[:,col])==abs(c))[0][0]>=col: #Caso o maior valor esteja em posição válida para se tornar o novo pivot
                return(np.where(np.abs(mat[:,col])==abs(c))[0][0]) #Retorna a posição


    def pivotparcial(mat:np.array,row=0,col=0): 

        maior = maiorargpivot(mat,col) #Encontra o maior elemento da linha

        if row<maior:
            mat[row],mat[maior] = mat[maior].copy(),mat[row].copy()

        mat[row] = mat[row]/mat[row,col]
        for l in range(row+1,len(mat)):
            if mat[l,col]!= 0:
                mat[l] = mat[l] - mat[l,col]/mat[row,col] * mat[row]
    
    for c in range(len(mat)-1):
        pivotparcial(mat,c,c)
        if steps:
            print(mat)
    print(mat)
    

In [71]:
matriz5 = np.array([0,1,2,3,4,
                    2,0,1,-1,0,
                    3,-2,0,1,2,
                    0,1,-2,0,2,
                    1,3,-2,1,0
                    ],dtype=np.float32).reshape(5,5)
print(matriz5)
res5 = np.array([1,-1,5,3,10])

gauss_pivotparcial(matriz5)#,steps=True)
np.linalg.solve(matriz5,res5)


[[ 0.  1.  2.  3.  4.]
 [ 2.  0.  1. -1.  0.]
 [ 3. -2.  0.  1.  2.]
 [ 0.  1. -2.  0.  2.]
 [ 1.  3. -2.  1.  0.]]
[[ 1.         -0.6666667   0.          0.33333334  0.6666667 ]
 [ 0.          1.         -0.54545456  0.18181817 -0.18181819]
 [ 0.          0.          1.          1.1071428   1.6428571 ]
 [-0.         -0.         -0.          1.          1.0280373 ]
 [ 0.          0.          0.          0.          3.1028037 ]]


array([-1.26328711, -0.32866537,  0.05206533, -0.31325281,  3.2228916 ])

# Fatoração LU
# 6)

In [72]:
def fatoraLU(A):  
    U = np.copy(A) 
    n = np.shape(U)[0] #nº de Linhas da matriz
    L = np.eye(n) #Identidade
    cont = 0 
    for j in np.arange(n-1): #Pelas colunas
        for i in np.arange(j+1,n):  #Pelas linhas

            L[i,j] = U[i,j]/U[j,j] #representa o m # no L são salvos os multiplicadores da posição pelo pivot
            U[i] = U[i] - L[i,j]*U[j]

    return L, U





In [73]:
#Analisa a questão 2 por LU
#Recria a matriz do exercício
mat = np.array([2,2,1,1,
                1,-1,2,-1,
                3,2,-3,-2,
                4,3,2,1],dtype='float32').reshape(4,4)

l,u = fatoraLU(mat)
print("L:")
print(np.around(l,3))
print("U")
print(np.around(u,3))

#Prova real
print("A=LU")
print(np.around(l@u,3))


L:
[[1.    0.    0.    0.   ]
 [0.5   1.    0.    0.   ]
 [1.5   0.5   1.    0.   ]
 [2.    0.5   0.143 1.   ]]
U
[[ 2.     2.     1.     1.   ]
 [ 0.    -2.     1.5   -1.5  ]
 [ 0.     0.    -5.25  -2.75 ]
 [ 0.     0.     0.     0.143]]
A=LU
[[ 2.  2.  1.  1.]
 [ 1. -1.  2. -1.]
 [ 3.  2. -3. -2.]
 [ 4.  3.  2.  1.]]


# 8)

In [74]:
mat8 = np.array([2,4,0,4,6,3,-6,-10,0]).reshape(3,3)
l,u = fatoraLU(mat8)


In [75]:
#i)
resulti = np.array([2,1,-6])

#ii)
resultii = np.array([1]*3)

#iii) 
resultiii = np.array([2,2,0])

#iv)
resultiv = np.array([1,2,3])

print('l:\n',l)
print('u:\n',u)

l:
 [[ 1.  0.  0.]
 [ 2.  1.  0.]
 [-3. -1.  1.]]
u:
 [[ 2  4  0]
 [ 0 -2  3]
 [ 0  0  3]]


# Gauss - Jacobi

    Transformar Ax = b em x = Cx + g
    x**(k+1) = Cx**(k) + g

    - Transforma A em uma matriz Diagonal + Matriz Diagonal nula
    - Manipular

https://prnt.sc/26i6nc6 Cálculos

https://prnt.sc/26i6nvb Resumo



In [76]:
def jacobi(A,x:np.ndarray,b:np.ndarray,precisao:float,xlist=None):
    """Realiza o método iterativo de Gauss-Jacobi para aproximar o valor de x uma vez

    Args:
        A (np.matrix): Original coef matrix of Ax = b
        x (np.ndarray): Initial guess of the values that satisfies the linear system
        b (np.ndarray): Vector of results from the linear system
    """

    def maiorargpivot(mat,col):

        """Descobre o maior pivot da coluna atual e retorna seu index, 
        para realizar a permutação

        Args:
            mat ([np.ndarray]): [numpy matrix]
            col ([int]): [column index]
        
        Returns:
            Maior index da coluna
        """
        ordenada=np.sort(np.abs(mat[:,col]))[::-1]

        for i,c in enumerate(ordenada):
            if np.where(np.abs(mat[:,col])==abs(c))[0][0]>=col: #Caso o maior valor esteja em posição válida para se tornar o novo pivot
                return(np.where(np.abs(mat[:,col])==abs(c))[0][0]) #Retorna a posição
    
    if xlist is None:
        xlist = []
    if len(xlist)>1 and max(abs(xlist[-1] - xlist[-2]))<precisao: #Critério de parada
        return x
    
    # Organiza a matriz de forma a satisfazer o critério de convergência da melhor forma
    for ind,l in enumerate(A):
        maior_da_coluna = maiorargpivot(A,ind)
        if maior_da_coluna!= ind:
            A[ind],A[maior_da_coluna] = A[maior_da_coluna].copy(),l.copy()

    
    # diagflat cria uma matriz com apenas a diagonal definida, restante 0. np.diagonal obtém um vetor que representa a diagonal da Matriz
    
    D = np.diagflat(np.diagonal(A)) #Matriz Diagonal com restante 0
    M = A - D #Matriz com a diagonal zerada
    Dinv = np.diagflat(1/np.diagonal(A)) #np.linalg.inv(D)
    C = -(Dinv@M)
    g = (Dinv@b)
    x = C@x + g #Próximo x

    print(x)
    xlist.append(x)
    
    return jacobi(A,x,b,precisao,xlist) #Recursão


exemplejacobi = np.array([10,2,1,1,5,1,2,3,10]).reshape(3,3)
res = np.array([7,-8,6])
jacobi(exemplejacobi,np.array([.7,-1.5,.6]),res,.0001)


[ 0.94 -1.86  0.91]
[ 0.981 -1.97   0.97 ]
[ 0.997  -1.9902  0.9948]
[ 0.99856 -1.99836  0.99766]
[ 0.999906 -1.999244  0.999796]
[ 0.9998692 -1.9999404  0.999792 ]
[ 1.00000888 -1.99993224  1.00000828]
[ 0.99998562 -2.00000343  0.9999779 ]


array([ 0.99998562, -2.00000343,  0.9999779 ])

# Gauss - Seidel

In [77]:
def seidel(A,x:np.ndarray,b:np.ndarray,precisao:float,xlist=None):
    """Realiza o método iterativo de Gauss-Jacobi para aproximar o valor de x uma vez

    Args:
        A (np.matrix): Original coef matrix of Ax = b
        x (np.ndarray): Initial guess of the values that satisfies the linear system
        b (np.ndarray): Vector of results from the linear system
    """
    
    def maiorargpivot(mat,col):

        """Descobre o maior pivot da coluna atual e retorna seu index, 
        para realizar a permutação

        Args:
            mat ([np.ndarray]): [numpy matrix]
            col ([int]): [column index]
        
        Returns:
            Maior index da coluna
        """
        ordenada=np.sort(np.abs(mat[:,col]))[::-1]

        for i,c in enumerate(ordenada):
            if np.where(np.abs(mat[:,col])==abs(c))[0][0]>=col: #Caso o maior valor esteja em posição válida para se tornar o novo pivot
                return(np.where(np.abs(mat[:,col])==abs(c))[0][0]) #Retorna a posição
    # Organiza a matriz de forma a satisfazer o critério de convergência da melhor forma
    
    if xlist is None:
        xlist = []

    for ind,l in enumerate(A):
        maior_da_coluna = maiorargpivot(A,ind)
        if maior_da_coluna!= ind:
            A[ind],A[maior_da_coluna] = A[maior_da_coluna].copy(),l.copy()

    if len(xlist)>1 and max(np.abs(xlist[-1] - xlist[-2]))<precisao: #Critério de parada
        return xlist[-1]

    # diagflat cria uma matriz com apenas a diagonal definida, restante 0. np.diagonal obtém um vetor que representa a diagonal da Matriz
    D = np.diagflat(np.diagonal(A)) #Matriz Diagonal com restante 0
    M = A - D # Matriz com a diagonal zerada
    Dinv = np.diagflat(1/np.diagonal(A))
    C = -(Dinv@M) # @ Representa uma multiplicação de matrizes, equivale a np.matmul (https://numpy.org/doc/stable/reference/generated/numpy.matmul.html)
    g = (Dinv@b)

    print(x)

    #Iteração 
    for n in range(len(x)):
        #Para cada iteração, utiliza o valor ja calculado, que foi salvo em x
        x[n] = (Dinv[n,n]*(b[n]-sum(M[n]*x)))
        
    xlist.append(x)


    return seidel(A,x,b,precisao,xlist) #Recursão


exempleseidel = np.array([10,2,1,1,5,1,2,3,10],dtype = 'float').reshape(3,3)
res = np.array([7,-8,6],dtype='float')
seidel(exempleseidel,np.array([.7,-1.5,.6],dtype='float'),res,.001)



[ 0.7 -1.5  0.6]
[ 0.94   -1.908   0.9844]


array([ 0.98316  , -1.993512 ,  1.0014216])

# 10)

In [78]:
mat10i = np.array([10,1,1,1,10,1,1,1,10]).reshape(3,3)
res10i = np.array([12]*3)
seidel(mat10i,np.zeros(3),res10i,.0001)

[0. 0. 0.]
[1.2   1.08  0.972]


array([0.9948  , 1.00332 , 1.000188])

In [79]:
mat10ii = np.array([4,-1,0,0,-1,4,-1,0,0,-1,4,-1,0,0,-1,4]).reshape(4,4)
res10ii = np.ones(4)
print(seidel(mat10ii,np.array([.4,.4,.4,.4]),res10ii,.0001))

[0.4 0.4 0.4 0.4]
[0.35       0.4375     0.459375   0.36484375]
[0.359375   0.4546875  0.45488281 0.3637207 ]


# 11)

In [80]:
mat11 = np.array([3,1,2,5],dtype=np.float32).reshape(2,2)
res11 = np.array([2,-3])

print(jacobi(mat11,np.array([0.9,1.2]),res11,10**-5))
np.linalg.solve(mat11,res11)

[ 0.26666667 -0.96000001]
[ 0.9866667  -0.70666668]
[ 0.90222225 -0.9946667 ]
[ 0.99822226 -0.96088892]
[ 0.986963   -0.99928892]
[ 0.999763   -0.99478522]
[ 0.99826177 -0.99990522]
[ 0.99996844 -0.99930472]
[ 0.99976827 -0.99998739]
[ 0.99999583 -0.99990732]
[ 0.99996914 -0.99999835]
[ 0.99999948 -0.99998767]
[ 0.99999592 -0.99999981]
[ 0.99999997 -0.99999838]
[ 0.99999997 -0.99999838]


array([ 1., -1.])

# 12)

In [81]:
lkc = np.array([100,-50,0,0,
-50,100,-50,0,
0,-50,100,-50,
0,0,-50,52],dtype=np.float32).reshape(4,4)

chute = np.array([100]*4)
b = np.array([127*50,0,0,0]) 

jacobi(lkc,chute,b,precisao =.001)



[113.49999858 100.         100.          96.15384936]
[113.49999858 106.74999929  98.07692468  96.15384936]
[116.87499823 105.78846163 101.45192433  94.30473842]
[116.3942294  109.16346128 100.04660002  97.54993049]
[118.08172922 108.22041471 103.35669588  96.19865708]
[117.61020594 110.71921255 102.2095359   99.38144167]
[118.85960486 109.90987092 105.05032711  98.27840318]
[118.45493404 111.95496598 104.09413705 101.00993328]
[119.47748157 111.27453554 106.48244963 100.09051973]
[119.13726635 112.9799656  105.68252764 102.38697422]
[119.98998138 112.409897   107.68346991 101.61781843]
[119.70494708 113.83672565 107.01385771 103.54180145]
[120.4183614  113.3594024  108.68926355 102.89794354]
[120.17969978 114.55381248 108.12867297 104.50891075]
[120.77690482 114.15418637 109.53136161 103.96988132]
[120.57709177 115.15413321 109.06203385 105.31862045]
[121.07706519 114.81956281 110.23637683 104.86734374]
[120.90977998 115.65672101 109.84345327 105.99651972]
[121.32835909 115.37661663 1

array([122.61942596, 118.23858075, 113.8591068 , 109.47898924])

# 13)

In [82]:
mat13 = np.array([4,1,1,1,
                2,-8,1,-1,
                1,2,-5,1,
                1,1,1,-4],dtype='float32').reshape(4,4)

b13 = np.array([7,-6,-1,-1],dtype='float32')
print(seidel(mat13,x=np.array([3,1,0,-1],dtype='float32'),b=b13,precisao=10**-4))

[ 3.  1.  0. -1.]
[1.75     1.3125   0.875    1.234375]
[0.89453125 0.92871094 0.99726564 0.95512694]


# 14)

In [83]:
mat14 = np.array([5,-1,2,-1,1,9,-3,4,0,3,-7,2,-2,2,-3,10],dtype='float32').reshape(4,4)
b14= np.array([5,26,-7,33])
x14=np.array([0,3,1,4])
jacobi(mat14,x=x14,b=b14,precisao = 10**-3)

[2.00000003 1.44444446 3.42857163 3.00000005]
[0.51746026 2.47619056 2.47619063 4.43968269]
[1.39269842 1.6835979  3.32970548 3.6511112 ]
[0.73505964 2.2213304  2.76471674 4.24073184]
[1.18652577 1.84401817 3.16363658 3.83216095]
[0.8697812  2.10841562 2.88519679 4.11759258]
[1.09112294 1.92393768 3.08006188 3.91783223]
[0.93632924 2.05308157 2.94392552 4.0574557 ]
[1.04453726 1.96284721 3.03916532 3.95982727]
[0.96886878 2.02596111 2.97259961 4.02808769]
[1.02176993 1.98184218 3.01915141 3.9803615 ]
[0.98478019 2.01269318 2.98660724 4.01373105]
[1.01064197 1.99112418 3.00936326 3.99039966]
[0.99255948 2.0062055  2.99345329 4.00671262]
[1.00520232 1.99566114 3.00457756 3.99530686]
[0.99636259 2.00303369 2.99679976 4.00328159]
[1.00254317 1.99787896 3.00223791 3.99770579]
[0.9982218  2.00148308 2.99843566 4.0016043 ]
[1.00124323 1.99896315 3.00109414 3.99887852]
[0.99913069 2.00072505 2.99923538 4.00078434]
[1.00060774 1.99949316 3.000535   3.99945182]
[0.99957501 2.00035448 2.99962632 

array([1.00029708, 1.99975226, 3.00026165, 3.99973209])