# Imports Base

In [59]:
import numpy as np
from fractions import Fraction
import sympy as sy


# 1)

In [60]:
#Realiza o método de eliminação de gauss iterativamente. Considera que não há zeros na diagonal principal
def pivotamento(mat):
    def pivot(mat,col=0,row=0):

        #Elimina a chance do elemento divisor ser 0
        r=1        
        while mat[row,col] == 0:
            mat[:,col],mat[:,col+r] = mat[:,col+r].copy(),mat[:,col].copy()
            r+=1

        mat[row] = mat[row]/mat[row,col]

        for l in range(row+1,len(mat)):
            mat[l] = mat[l] - mat[l,col]/mat[row,col] * mat[row]
            
    for r in range(len(mat)): #Realiza o pivotamento para cada elemento da diagonal
        pivot(mat,r,r)
        #print('\n',mat) #Printa passo a passo

#Algoritmo utilizado na questão 2


# 2)

In [61]:
#Cria a matriz do exercício
mat = np.array([2,2,1,1,7,
                1,-1,2,-1,1,
                3,2,-3,-2,4,
                4,3,2,1,12],dtype=np.float32).reshape(4,5)
mat

array([[ 2.,  2.,  1.,  1.,  7.],
       [ 1., -1.,  2., -1.,  1.],
       [ 3.,  2., -3., -2.,  4.],
       [ 4.,  3.,  2.,  1., 12.]], dtype=float32)

In [62]:
pivotamento(mat)
mat

array([[ 1.        ,  1.        ,  0.5       ,  0.5       ,  3.5       ],
       [-0.        ,  1.        , -0.75      ,  0.75      ,  1.25      ],
       [-0.        , -0.        ,  1.        ,  0.52380955,  1.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ,  0.        ]],
      dtype=float32)

# 3)

In [63]:
n=10
mat3 = [[0]*n for _ in range(n)]
mat3[0][:2] = [2,-2]
mat3[n-1][-2:] = [-1,2]
for l in range(1,n-1): #linha
    mat3[l][l-1] = -1
    mat3[l][l] = 2
    mat3[l][l+1] = -1
    
mat3

[[2, -2, 0, 0, 0, 0, 0, 0, 0, 0],
 [-1, 2, -1, 0, 0, 0, 0, 0, 0, 0],
 [0, -1, 2, -1, 0, 0, 0, 0, 0, 0],
 [0, 0, -1, 2, -1, 0, 0, 0, 0, 0],
 [0, 0, 0, -1, 2, -1, 0, 0, 0, 0],
 [0, 0, 0, 0, -1, 2, -1, 0, 0, 0],
 [0, 0, 0, 0, 0, -1, 2, -1, 0, 0],
 [0, 0, 0, 0, 0, 0, -1, 2, -1, 0],
 [0, 0, 0, 0, 0, 0, 0, -1, 2, -1],
 [0, 0, 0, 0, 0, 0, 0, 0, -1, 2]]

# Fatoração LDU

In [64]:
def LDU(A):
    U = np.copy(A)
    D = np.diagflat(np.diagonal(U))
    n = np.shape(U)[0] #nº de Linhas da matriz
    L = np.eye(n) #Identidade
    cont = 0 
    for j in np.arange(n-1): #Pelas colunas

        for i in np.arange(j+1,n):  #Pelas linhas

            L[i,j] = U[i,j]/U[j,j] #representa o m # no L são salvos os multiplicadores da posição pelo pivot
            U[i] = U[i] - L[i,j]*U[j]
    

    return L, D, U



In [65]:
x = np.array([[1,2],[3,4]])


Fatora LDU:

Fatora Ly = B
descobre um vetor y, que substitui o resultado
Dz = y

encontra um vetor z
Ux = z

Encontra finalmente x

# 5)
    Estratégia de pivoteamento parcial
    No início de cada eliminação de Gauss, trocando as linhas se necessário,
    escolher para o pivô o maior 𝑎𝑖𝑗 da coluna 𝑗 (com 𝑖 ≥ 𝑗).

In [66]:
matriz5 = np.array([0,1,2,3,4,
                    2,0,1,-1,0,
                    3,-2,0,1,2,
                    0,1,-2,0,2,
                    1,3,-2,1,0
                    ],dtype=np.float32).reshape(5,5)
col = 1
ordenada=np.sort(np.abs(matriz5[:,col]))[::-1]

for i,c in enumerate(ordenada):
    if np.where(np.abs(matriz5[:,col])==abs(c))[0][0]>=col:
        return(np.where(np.abs(matriz5[:,col])==abs(c))[0][0])

SyntaxError: 'return' outside function (Temp/ipykernel_11132/1288390526.py, line 12)

In [ ]:
def gauss_pivotparcial(mat,steps=False):

    def maiorargpivot(mat,col):
        """Descobre o maior pivot da coluna atual e retorna seu index, 
        para realizar a permutação

        Args:
            mat ([np.ndarray]): [numpy matrix]
            col ([int]): [column index]
        
        Returns:
            Maior index da coluna
        """
        ordenada=np.sort(np.abs(mat[:,col]))[::-1]

        for i,c in enumerate(ordenada):
            if np.where(np.abs(mat[:,col])==abs(c))[0][0]>=col: #Caso o maior valor esteja em posição válida para se tornar o novo pivot
                return(np.where(np.abs(mat[:,col])==abs(c))[0][0]) #Retorna a posição


    def pivotparcial(mat:np.array,row=0,col=0): 

        maior = maiorargpivot(mat,col) #Encontra o maior elemento da linha

        if row<maior:
            mat[row],mat[maior] = mat[maior].copy(),mat[row].copy()

        mat[row] = mat[row]/mat[row,col]
        for l in range(row+1,len(mat)):
            if mat[l,col]!= 0:
                mat[l] = mat[l] - mat[l,col]/mat[row,col] * mat[row]
    
    for c in range(len(mat)-1):
        pivotparcial(mat,c,c)
        if steps:
            print(mat)
    print(mat)
    

In [ ]:
matriz5 = np.array([0,1,2,3,4,
                    2,0,1,-1,0,
                    3,-2,0,1,2,
                    0,1,-2,0,2,
                    1,3,-2,1,0
                    ],dtype=np.float32).reshape(5,5)
print(matriz)
res5 = np.array([8,3,9,5,6])

#gauss_pivotparcial(matriz)

np.linalg.solve(matriz5,res5)

[[ 1.         -0.6666667   0.          0.33333334  0.6666667 ]
 [ 0.          1.         -0.54545456  0.18181817 -0.18181819]
 [ 0.          0.          1.          1.1071428   1.6428571 ]
 [ 0.          0.          0.          1.4285715   4.5714283 ]
 [ 0.          0.          0.         -3.8214285  -3.9285712 ]]


array([ 2.14457831,  0.6626506 , -0.57831325,  0.71084337,  1.59036145])

# Fatoração LU
# 6)

In [ ]:
def fatoraLU(A):  
    U = np.copy(A) 
    n = np.shape(U)[0] #nº de Linhas da matriz
    L = np.eye(n) #Identidade
    cont = 0 
    for j in np.arange(n-1): #Pelas colunas
        '''while U[j,j]==0:
            print(U[j])
            cont+=1
            U[j],U[j+cont] = U[j+cont].copy(),U[j].copy()'''

        for i in np.arange(j+1,n):  #Pelas linhas

            L[i,j] = U[i,j]/U[j,j] #representa o m # no L são salvos os multiplicadores da posição pelo pivot
            U[i] = U[i] - L[i,j]*U[j]
            
            
            

    return L, U

def solveL(L,b):

    y = np.zeros(L.shape[1])
    for i in range(len(b)+1):
        soma = 0
        for j in range(i):
            soma += L[i][j]*y[j]

        y[i] = b[i]-soma

    return y

def solveU(U,y):
    n = len(y)-1
#Vetor cheio de 0 de n de tamanho  
    x = np.zeros(y.shape)
    x[n] = b[n]/U[n][n]

    for i in range(n-1,0,-1):
        soma = 0
        for j in range(i-1,n+2):
            soma = soma + U[i][j]*x[j]

        x[i] = (b[i]-soma)/U[i][i]

    return x



In [ ]:
#Resolvendo a questão 2 por LU
#Recria a matriz do exercício
mat = np.array([2,2,1,1,
                1,-1,2,-1,
                3,2,-3,-2,
                4,3,2,1],dtype='float32').reshape(4,4)

l,u = fatoraLU(mat)
print(l)
print(u)

#Conferindo
print(l@u)


[[1.         0.         0.         0.        ]
 [0.5        1.         0.         0.        ]
 [1.5        0.5        1.         0.        ]
 [2.         0.5        0.14285715 1.        ]]
[[ 2.0000000e+00  2.0000000e+00  1.0000000e+00  1.0000000e+00]
 [ 0.0000000e+00 -2.0000000e+00  1.5000000e+00 -1.5000000e+00]
 [ 0.0000000e+00  0.0000000e+00 -5.2500000e+00 -2.7500000e+00]
 [ 0.0000000e+00  0.0000000e+00  5.9604645e-08  1.4285716e-01]]
[[ 2.          2.          1.          1.        ]
 [ 1.         -1.          2.         -1.        ]
 [ 3.          2.         -3.         -2.        ]
 [ 4.          3.          2.00000003  1.        ]]


# 8)

In [ ]:
mat8 = np.array([2,4,0,4,6,3,-6,-10,0]).reshape(3,3)
l,u = fatoraLU(mat8)


In [ ]:
#i)
resulti = np.array([2,1,-6])

#ii)
resultii = np.array([1]*3)

#iii) 
resultiii = np.array([2,2,0])

#iv)
resultiv = np.array([1,2,3])

print('l:\n',l)
print('u:\n',u)

l:
 [[ 1.  0.  0.]
 [ 2.  1.  0.]
 [-3. -1.  1.]]
u:
 [[ 2  4  0]
 [ 0 -2  3]
 [ 0  0  3]]


In [ ]:
np.linalg.solve(mat8,resultiv)

array([-5.5,  3. ,  2. ])

# Gauss - Jacobi

    Transformar Ax = b em x = Cx + g
    x**(k+1) = Cx**(k) + g

    - Transforma A em uma matriz Diagonal + Matriz Diagonal nula
    - Manipular

https://prnt.sc/26i6nc6 Cálculos

https://prnt.sc/26i6nvb Resumo



In [ ]:
def jacobi(A,x:np.ndarray,b:np.ndarray,precisao:float,xlist=None):
    """Realiza o método iterativo de Gauss-Jacobi para aproximar o valor de x uma vez

    Args:
        A (np.matrix): Original coef matrix of Ax = b
        x (np.ndarray): Inicial guess of the values that satisfies the linear system
        b (np.ndarray): Vector of results from the linear system
    """

    def maiorargpivot(mat,col):

        """Descobre o maior pivot da coluna atual e retorna seu index, 
        para realizar a permutação

        Args:
            mat ([np.ndarray]): [numpy matrix]
            col ([int]): [column index]
        
        Returns:
            Maior index da coluna
        """
        ordenada=np.sort(np.abs(mat[:,col]))[::-1]

        for i,c in enumerate(ordenada):
            if np.where(np.abs(mat[:,col])==abs(c))[0][0]>=col: #Caso o maior valor esteja em posição válida para se tornar o novo pivot
                return(np.where(np.abs(mat[:,col])==abs(c))[0][0]) #Retorna a posição
    
    if xlist is None:
        xlist = []
    if len(xlist)>1 and max(abs(xlist[-1] - xlist[-2]))<precisao: #Critério de parada
        return x
    
    # Organiza a matriz de forma a satisfazer o critério de convergência da melhor forma
    for ind,l in enumerate(A):
        maior_da_coluna = maiorargpivot(A,ind)
        if maior_da_coluna!= ind:
            A[ind],A[maior_da_coluna] = A[maior_da_coluna].copy(),l.copy()

    
    # diagflat cria uma matriz com apenas a diagonal definida, restante 0. np.diagonal obtém um vetor que representa a diagonal da Matriz
    
    D = np.diagflat(np.diagonal(A)) #Matriz Diagonal com restante 0
    M = A - D #Matriz com a diagonal zerada
    Dinv = np.diagflat(1/np.diagonal(A)) #np.linalg.inv(D)
    C = -(Dinv@M)
    g = (Dinv@b)
    x = C@x + g #Próximo x

    print(x)
    xlist.append(x)
    
    return jacobi(A,x,b,precisao,xlist) #Recursão


exemplejacobi = np.array([10,2,1,1,5,1,2,3,10]).reshape(3,3)
res = np.array([7,-8,6])
jacobi(exemplejacobi,np.array([.7,-1.5,.6]),res,.0001)


[ 0.94 -1.86  0.91]
[ 0.981 -1.97   0.97 ]
[ 0.997  -1.9902  0.9948]
[ 0.99856 -1.99836  0.99766]
[ 0.999906 -1.999244  0.999796]
[ 0.9998692 -1.9999404  0.999792 ]
[ 1.00000888 -1.99993224  1.00000828]
[ 0.99998562 -2.00000343  0.9999779 ]


array([ 0.99998562, -2.00000343,  0.9999779 ])

In [83]:
def seidel(A,x:np.ndarray,b:np.ndarray,precisao:float,xlist=None):
    """Realiza o método iterativo de Gauss-Jacobi para aproximar o valor de x uma vez

    Args:
        A (np.matrix): Original coef matrix of Ax = b
        x (np.ndarray): Initial guess of the values that satisfies the linear system
        b (np.ndarray): Vector of results from the linear system
    """
    
    def maiorargpivot(mat,col):

        """Descobre o maior pivot da coluna atual e retorna seu index, 
        para realizar a permutação

        Args:
            mat ([np.ndarray]): [numpy matrix]
            col ([int]): [column index]
        
        Returns:
            Maior index da coluna
        """
        ordenada=np.sort(np.abs(mat[:,col]))[::-1]

        for i,c in enumerate(ordenada):
            if np.where(np.abs(mat[:,col])==abs(c))[0][0]>=col: #Caso o maior valor esteja em posição válida para se tornar o novo pivot
                return(np.where(np.abs(mat[:,col])==abs(c))[0][0]) #Retorna a posição
    # Organiza a matriz de forma a satisfazer o critério de convergência da melhor forma
    
    if xlist is None:
        xlist = []

    for ind,l in enumerate(A):
        maior_da_coluna = maiorargpivot(A,ind)
        if maior_da_coluna!= ind:
            A[ind],A[maior_da_coluna] = A[maior_da_coluna].copy(),l.copy()

    if len(xlist)>1 and max(abs(xlist[-1] - xlist[-2]))<precisao: #Critério de parada
       
        return x

    # diagflat cria uma matriz com apenas a diagonal definida, restante 0. np.diagonal obtém um vetor que representa a diagonal da Matriz
    D = np.diagflat(np.diagonal(A)) #Matriz Diagonal com restante 0
    M = A - D # Matriz com a diagonal zerada
    Dinv = np.diagflat(1/np.diagonal(A))
    C = -(Dinv@M) # @ Representa uma multiplicação de matrizes, equivale a np.matmul (https://numpy.org/doc/stable/reference/generated/numpy.matmul.html)
    g = (Dinv@b)

    print(x)

    #Iteração 
    for n in range(len(x)):
        #Para cada iteração, utiliza o valor ja calculado, que foi salvo em x
        x[n] = round(Dinv[n,n]*(b[n]-sum(M[n]*x)),10)
        print('dinv',Dinv[n,n])
        print('bn,mn,x',b[n],M[n],x)
        print('bn-sum',b[n]-sum(M[n]*x))
        print('mult',Dinv[n,n]*(b[n]-sum(M[n]*x)))
        print()
    xlist.append(x)


    return seidel(A,x,b,precisao,xlist) #Recursão


exempleseidel = np.array([10,2,1,1,5,1,2,3,10],dtype = 'float32').reshape(3,3)
res = np.array([7,-8,6])
seidel(exempleseidel,np.array([.7,-1.5,.6]),res,.00001)
np.linalg.solve(exempleseidel,res)



[ 0.7 -1.5  0.6]
dinv 0.1
bn,mn,x 7 [0. 2. 1.] [ 0.94000001 -1.5         0.6       ]
bn-sum 9.4
mult 0.9400000140070915

dinv 0.2
bn,mn,x -8 [1. 0. 1.] [ 0.94000001 -1.90800003  0.6       ]
bn-sum -9.540000014
mult -1.9080000312314156

dinv 0.1
bn,mn,x 6 [2. 3. 0.] [ 0.94000001 -1.90800003  0.98440002]
bn-sum 9.8440000656
mult 0.9844000212287032

[ 0.94000001 -1.90800003  0.98440002]
dinv 0.1
bn,mn,x 7 [0. 2. 1.] [ 0.98316002 -1.90800003  0.98440002]
bn-sum 9.8316000412
mult 0.9831600187702256

dinv 0.2
bn,mn,x -8 [1. 0. 1.] [ 0.98316002 -1.99351204  0.98440002]
bn-sum -9.96756004
mult -1.993512037705644

dinv 0.1
bn,mn,x 6 [2. 3. 0.] [ 0.98316002 -1.99351204  1.00142162]
bn-sum 10.014216075499998
mult 1.0014216224723447



array([ 1., -2.,  1.])

# 12)

In [ ]:
lkc = np.array([3,-1,0,0,
-1,3,-1,0,
0,-1,3,-1,
0,0,-1,3],dtype=np.float32).reshape(4,4)

chute = np.array([50,20,10,5])
b = np.array([127,0,0,0]) 

jacobi(lkc,chute,b,precisao =.001)



[49.00000146 20.0000006   8.33333358  3.33333343]
[49.00000166 19.11111225  7.77777824  2.77777794]
[48.70370553 18.9259272   7.29629695  2.59259282]
[48.64197718 18.66666805  7.17284022  2.43209906]
[48.55555746 18.60493969  7.03292258  2.39094681]
[48.53498134 18.5294939   6.99862904  2.3443076 ]
[48.50983275 18.51120401  6.95793404  2.33287642]
[48.50373612 18.48925615  6.94802702  2.31931142]
[48.49642016 18.4839216   6.93618939  2.31600907]
[48.49464198 18.47753707  6.93331043  2.3120632 ]
[48.4925138  18.47598469  6.92986696  2.31110355]
[48.49199634 18.47412747  6.92902962  2.30995572]
[48.49137727 18.47367587  6.92802794  2.30967661]
[48.49122674 18.47313562  6.92778437  2.30934271]


array([48.49122674, 18.47313562,  6.92778437,  2.30934271])

# 13)

In [84]:
mat13 = np.array([4,1,1,1,
                2,-8,1,-1,
                1,2,-5,1,
                1,1,1,-4],dtype='float32').reshape(4,4)

b13 = np.array([7,-6,-1,-1])
seidel(mat13,x=np.array([3,1,0,-1]),b=b13,precisao=10**-4)
np.linalg.solve(mat13,b13)

[ 3  1  0 -1]
dinv 0.25
bn,mn,x 7 [0. 1. 1. 1.] [ 1  1  0 -1]
bn-sum 7.0
mult 1.75

dinv -0.125
bn,mn,x -6 [ 2.  0.  1. -1.] [ 1  1  0 -1]
bn-sum -9.0
mult 1.125

dinv -0.2
bn,mn,x -1 [1. 2. 0. 1.] [ 1  1  0 -1]
bn-sum -3.0
mult 0.6000000089406967

dinv -0.25
bn,mn,x -1 [1. 1. 1. 0.] [1 1 0 0]
bn-sum -3.0
mult 0.75

[1 1 0 0]
dinv 0.25
bn,mn,x 7 [0. 1. 1. 1.] [1 1 0 0]
bn-sum 6.0
mult 1.5

dinv -0.125
bn,mn,x -6 [ 2.  0.  1. -1.] [1 1 0 0]
bn-sum -8.0
mult 1.0

dinv -0.2
bn,mn,x -1 [1. 2. 0. 1.] [1 1 0 0]
bn-sum -4.0
mult 0.800000011920929

dinv -0.25
bn,mn,x -1 [1. 1. 1. 0.] [1 1 0 0]
bn-sum -3.0
mult 0.75



array([1., 1., 1., 1.])

# 14)

In [ ]:
mat14 = np.array([5,-1,2,-1,1,9,-3,4,0,3,-7,2,-2,2,-3,10],dtype='float32').reshape(4,4)
b14= np.array([5,26,-7,33])
x14=np.array([2,3,4,5])
jacobi(mat14,x=x14,b=b14,precisao = 10**-3)
np.linalg.solve(mat14,b14)

[1.00000001 1.77777782 3.71428593 4.30000009]
[0.72984122 2.10476197 2.9904764  4.25873031]
[1.07650791 1.9118519  3.11882111 3.92215885]
[0.91927372 2.06570226 2.93998207 4.06857762]
[1.05086316 1.95848471 3.04775188 3.95270899]
[0.963138   2.03128409 2.96869618 4.03280134]
[1.02533863 1.97908283 3.02277945 3.97697972]
[0.98210075 2.01500902 2.98445844 4.01608508]
[1.01243546 1.9896594  3.01102834 3.98875596]
[0.99127175 2.00729178 2.99235589 4.0078638 ]
[1.00608877 1.99492679 3.00537201 3.99450284]
[0.99573714 2.00355736 2.99625531 4.00384408]
[1.00297818 1.99751698 3.00262306 3.99731263]
[0.99791671 2.00173787 2.99816819 4.00187924]
[1.00145616 1.99878569 3.00128189 3.99868631]
[0.99898166 2.0008494  2.99910441 4.00091874]
[1.00071188 1.99940633 3.00062669 3.99935786]
[0.99950217 2.00041523 2.99956226 4.0004492 ]
[1.000348   1.99970979 3.00030646 3.99968615]


array([1., 2., 3., 4.])