# Imports Base

In [45]:
import numpy as np
from fractions import Fraction
import sympy as sy


# 1)

In [46]:
#Realiza o método de eliminação de gauss iterativamente. Considera que não há zeros na diagonal principal
def pivotamento(mat):
    def pivot(mat,col=0,row=0):

        #Elimina a chance do elemento divisor ser 0
        r=1        
        while mat[row,col] == 0:
            mat[:,col],mat[:,col+r] = mat[:,col+r].copy(),mat[:,col].copy()
            r+=1
        mat[row] = mat[row]/mat[row,col]

        for l in range(row+1,len(mat)):
            mat[l] = mat[l] - mat[l,col]/mat[row,col] * mat[row]
            
    for r in range(len(mat)):
        pivot(mat,r,r)
        print('\n',mat)

#Algoritmo utilizado na questão 2


# 2)

In [47]:
#Cria a matriz do exercício
mat = np.array([2,2,1,1,7,
                1,-1,2,-1,1,
                3,2,-3,-2,4,
                4,3,2,1,12],dtype=np.float32).reshape(4,5)
mat

array([[ 2.,  2.,  1.,  1.,  7.],
       [ 1., -1.,  2., -1.,  1.],
       [ 3.,  2., -3., -2.,  4.],
       [ 4.,  3.,  2.,  1., 12.]], dtype=float32)

In [48]:
pivotamento(mat)


 [[ 1.   1.   0.5  0.5  3.5]
 [ 0.  -2.   1.5 -1.5 -2.5]
 [ 0.  -1.  -4.5 -3.5 -6.5]
 [ 0.  -1.   0.  -1.  -2. ]]

 [[ 1.    1.    0.5   0.5   3.5 ]
 [-0.    1.   -0.75  0.75  1.25]
 [ 0.    0.   -5.25 -2.75 -5.25]
 [ 0.    0.   -0.75 -0.25 -0.75]]

 [[ 1.          1.          0.5         0.5         3.5       ]
 [-0.          1.         -0.75        0.75        1.25      ]
 [-0.         -0.          1.          0.52380955  1.        ]
 [ 0.          0.          0.          0.14285716  0.        ]]

 [[ 1.          1.          0.5         0.5         3.5       ]
 [-0.          1.         -0.75        0.75        1.25      ]
 [-0.         -0.          1.          0.52380955  1.        ]
 [ 0.          0.          0.          1.          0.        ]]


# 5)
    Estratégia de pivoteamento parcial
    No início de cada eliminação de Gauss, trocando as linhas se necessário,
    escolher para o pivô o maior 𝑎𝑖𝑗 da coluna 𝑗 (com 𝑖 ≥ 𝑗).

In [64]:
def gauss_pivotparcial(mat):
    def pivotparcial(mat:np.array,row=0,col=0):

        maior = np.argmax(mat[row:,col]) #Encontra a linha com o maior pivot na coluna especificada
        mat[col],mat[maior] = mat[maior].copy(),mat[col].copy()
        print(mat)
        '''   r=1
            while mat[row,col] == 0:
                mat[:,col],mat[:,col+r] = mat[:,col+r].copy(),mat[:,col].copy()
                r+=1'''
        mat[row] = mat[row]/mat[row,col]
        print(mat)
        for l in range(row+1,len(mat)):
            mat[l] = mat[l] - mat[l,col]/mat[row,col] * mat[row]
    
    for c in range(len(mat)):
        pivotparcial(mat,c,c)
matriz = np.array([(2,4,6),(6,8,10)],dtype=np.float32)
gauss_pivotparcial(matriz)
matriz

[[ 6.  8. 10.]
 [ 2.  4.  6.]]
[[1.        1.3333334 1.6666666]
 [2.        4.        6.       ]]


array([[1.       , 1.3333334, 1.6666666],
       [0.       , 1.3333333, 2.6666667]], dtype=float32)

# Fatoração LU

In [ ]:
def fatoraLU(A):  
    U = np.copy(A)  
    n = np.shape(U)[0]  
    L = np.eye(n)  
    for j in np.arange(n-1):  
        for i in np.arange(j+1,n):  
            L[i,j] = U[i,j]/U[j,j]  
            for k in np.arange(j+1,n):  
                U[i,k] = U[i,k] - L[i,j]*U[j,k]  
            U[i,j] = 0  
    return L, U

# 8)

In [ ]:
mat8 = np.array([2,4,0,4,6,3,-6,-10,0]).reshape(3,3)
l,u = fatoraLU(mat8)

In [ ]:
#i)
resulti = np.array([2,1,-6])



[[ 1.  0.  0.]
 [ 2.  1.  0.]
 [-3. -1.  1.]]
[[  2.   4.   0.]
 [  4.   6.   3.]
 [ -6. -10.   0.]]


In [ ]:
#ii)
matii = np.array([2,4,0,4,6,3,-6,-10,0]).reshape(3,3)
resultii = np.array([1]*3)

l,u = fatoraLU(matii)

In [ ]:
#iii) 
matiii = np.array([2,4,0,4,6,3,-6,-10,0]).reshape(3,3)
resultiii = np.array([2,1,-6])

l,u = fatoraLU(mati)