# Estudo de sistemas lineares utilizando numpy
### Com foco em sistemas de solução única

In [1]:
import numpy as np

In [2]:
#Definindo um sistema linear em numpy
#x+2y+z=0
#x-y-z=5

sist = np.array([[1,2,1],[1,-1,-1]])
resp = np.array([0,5])


In [3]:
#testando determinante

rng = np.random.default_rng()
mat=rng.random((3,3))*(100)
print(np.linalg.det(mat))
mat

69944.70165168893


array([[23.25633578, 55.94190495, 77.15113992],
       [87.96326812, 76.6808474 , 52.69537056],
       [80.14460318, 57.67133982,  4.10629736]])

## Método de eliminação de Gauss

O Método da Eliminação de Gauss consiste em transformar o sistema
original em um sistema equivalente (que tem a mesma solução) com
matriz dos coeficientes triangular superior.

Pivô é o elemento base para zerar os elementos abaixo dele

In [4]:
#É possivel realizar operações elementares que nao alteram a solução do sistema, 
# como multiplicações, divisões por numero e soma e subtração de linhas

#Usando a matriz mat, temos
print(mat)

mat[0]=mat[0]/min(mat[0])

print(mat)

[[23.25633578 55.94190495 77.15113992]
 [87.96326812 76.6808474  52.69537056]
 [80.14460318 57.67133982  4.10629736]]
[[ 1.          2.40544794  3.31742458]
 [87.96326812 76.6808474  52.69537056]
 [80.14460318 57.67133982  4.10629736]]


# Fatoração LU
  https://www.ufrgs.br/reamat/CalculoNumerico/livro-py/sdsl-fatoracao_lu.html

In [5]:
def fatoraLU(A):  
    U = np.copy(A)  
    n = np.shape(U)[0]  
    L = np.eye(n)
    for j in np.arange(n-1):  
        for i in np.arange(j+1,n):  
            L[i,j] = U[i,j]/U[j,j]  
            for k in np.arange(j+1,n):  
                U[i,k] = U[i,k] - L[i,j]*U[j,k]  
            U[i,j] = 0  
    return L, U

In [12]:
np.array([1,2,3])@np.array([[1],[2],[3]])

array([14])