# Estudo de sistemas lineares utilizando numpy
### Com foco em sistemas de solução única

In [2]:
import numpy as np

In [3]:
#Definindo um sistema linear em numpy
#x+2y+z=0
#x-y-z=5

sist = np.array([[1,2,1],[1,-1,-1]])
resp = np.array([0,5])


In [28]:
#testando determinante

rng = np.random.default_rng()
mat=rng.random((3,3))*(100)
print(np.linalg.det(mat))
mat

338605.89470244094


array([[81.97979867, 99.99843194, 16.93535652],
       [74.82710884, 84.02909178, 73.60607692],
       [75.15283098, 17.72887444, 38.88737579]])

## Método de eliminação de Gauss

O Método da Eliminação de Gauss consiste em transformar o sistema
original em um sistema equivalente (que tem a mesma solução) com
matriz dos coeficientes triangular superior.

Pivô é o elemento base para zerar os elementos abaixo dele

In [29]:
#É possivel realizar operações elementares que nao alteram a solução do sistema, 
# como multiplicações, divisões por numero e soma e subtração de linhas

#Usando a matriz mat, temos
print(mat)

mat[0]=mat[0]/min(mat[0])

print(mat)

[[81.97979867 99.99843194 16.93535652]
 [74.82710884 84.02909178 73.60607692]
 [75.15283098 17.72887444 38.88737579]]
[[ 4.84074832  5.90471372  1.        ]
 [74.82710884 84.02909178 73.60607692]
 [75.15283098 17.72887444 38.88737579]]
